import Foundation

struct VideoOracleRGB: Equatable {
  let red: Double
  let green: Double
  let blue: Double

  init(red: Double, green: Double, blue: Double) {
    self.red = red
    self.green = green
    self.blue = blue
  }

  init(_ pixel: PiPMotionPixel) {
    self.init(
      red: Double(pixel.red),
      green: Double(pixel.green),
      blue: Double(pixel.blue)
    )
  }

  func distance(to other: Self) -> Double {
    let redDelta = red - other.red
    let greenDelta = green - other.green
    let blueDelta = blue - other.blue
    return (redDelta * redDelta + greenDelta * greenDelta + blueDelta * blueDelta)
      .squareRoot()
  }
}

struct SeekVideoOracleObservation: Equatable {
  let bandIndex: Int
  let secondsIntoBand: Double
  let background: VideoOracleRGB
  let backgroundDistance: Double
  let markerContrast: Double

  var timelineSeconds: Double {
    Double(bandIndex * 10) + secondsIntoBand
  }
}

/// Decodes the content contract generated by `generate-fixtures.sh` from an
/// actual captured video surface. Native time, wrapper state, and this pixel
/// oracle are deliberately independent evidence sources.
struct VideoOracleAnalyzer {
  private static let seekBandColors = [
    VideoOracleRGB(red: 0xC0, green: 0x20, blue: 0x20),
    VideoOracleRGB(red: 0x20, green: 0xA0, blue: 0x40),
    VideoOracleRGB(red: 0x20, green: 0x40, blue: 0xC0),
    VideoOracleRGB(red: 0xC0, green: 0xA0, blue: 0x20),
    VideoOracleRGB(red: 0xA0, green: 0x20, blue: 0xA0),
    VideoOracleRGB(red: 0x20, green: 0xA0, blue: 0xA0)
  ]

  func seekObservation(in frame: PiPMotionFrame) -> SeekVideoOracleObservation? {
    guard frame.width >= 32, frame.height >= 18 else { return nil }
    let background = meanColor(
      in: frame,
      xRange: scaledRange(0.05..<0.95, count: frame.width),
      yRange: scaledRange(0.05..<0.18, count: frame.height)
    )
    let matches = Self.seekBandColors.enumerated().map { index, color in
      (index: index, distance: background.distance(to: color))
    }.sorted { $0.distance < $1.distance }
    guard let match = matches.first, match.distance <= 110 else { return nil }

    let markerRows = scaledRange(0.28..<0.72, count: frame.height)
    let markerWidth = max(1, Int((Double(frame.width) * 24 / 640).rounded()))
    let columnScores = (0..<frame.width).map { x in
      var score = 0.0
      var samples = 0
      for y in markerRows {
        score += VideoOracleRGB(frame.pixels[y * frame.width + x])
          .distance(to: background)
        samples += 1
      }
      return samples == 0 ? 0 : score / Double(samples)
    }
    guard markerWidth <= columnScores.count else { return nil }

    var windowScore = columnScores.prefix(markerWidth).reduce(0, +)
    var bestStart = 0
    var bestScore = windowScore
    if markerWidth < columnScores.count {
      for start in 1...(columnScores.count - markerWidth) {
        windowScore += columnScores[start + markerWidth - 1]
        windowScore -= columnScores[start - 1]
        if windowScore > bestScore {
          bestScore = windowScore
          bestStart = start
        }
      }
    }
    let markerContrast = bestScore / Double(markerWidth)
    guard markerContrast >= 50 else { return nil }

    let markerX = Double(bestStart) * 640 / Double(frame.width)
    let secondsIntoBand = (markerX - 40) / 56
    guard (-0.25...10.25).contains(secondsIntoBand) else { return nil }
    return SeekVideoOracleObservation(
      bandIndex: match.index,
      secondsIntoBand: min(10, max(0, secondsIntoBand)),
      background: background,
      backgroundDistance: match.distance,
      markerContrast: markerContrast
    )
  }

  /// Returns the exact all-intra fixture frame, or nil when the captured color
  /// is too far from the 5×5×5 code grid or lies ambiguously between two codes.
  func allIntraFrameIndex(in frame: PiPMotionFrame) -> Int? {
    guard frame.width > 0, frame.height > 0 else { return nil }
    let observed = meanColor(
      in: frame,
      xRange: scaledRange(0.10..<0.90, count: frame.width),
      yRange: scaledRange(0.08..<0.20, count: frame.height)
    )
    let matches = (0..<120).map { index in
      (index: index, distance: observed.distance(to: Self.frameColor(index: index)))
    }.sorted { $0.distance < $1.distance }
    guard
      matches.count >= 2,
      matches[0].distance <= 60,
      matches[1].distance - matches[0].distance >= 8
    else { return nil }
    return matches[0].index
  }

  static func frameColor(index: Int) -> VideoOracleRGB {
    precondition((0..<120).contains(index))
    return VideoOracleRGB(
      red: Double(32 + (index % 5) * 48),
      green: Double(32 + ((index / 5) % 5) * 48),
      blue: Double(32 + ((index / 25) % 5) * 48)
    )
  }

  private func meanColor(
    in frame: PiPMotionFrame,
    xRange: Range<Int>,
    yRange: Range<Int>
  ) -> VideoOracleRGB {
    var red = 0.0
    var green = 0.0
    var blue = 0.0
    var count = 0
    let xStride = max(1, xRange.count / 160)
    let yStride = max(1, yRange.count / 90)
    for y in stride(from: yRange.lowerBound, to: yRange.upperBound, by: yStride) {
      for x in stride(from: xRange.lowerBound, to: xRange.upperBound, by: xStride) {
        let color = VideoOracleRGB(frame.pixels[y * frame.width + x])
        red += color.red
        green += color.green
        blue += color.blue
        count += 1
      }
    }
    return VideoOracleRGB(
      red: red / Double(max(1, count)),
      green: green / Double(max(1, count)),
      blue: blue / Double(max(1, count))
    )
  }

  private func scaledRange(_ range: Range<Double>, count: Int) -> Range<Int> {
    let lower = min(count - 1, max(0, Int((Double(count) * range.lowerBound).rounded(.down))))
    let upper = min(count, max(lower + 1, Int((Double(count) * range.upperBound).rounded(.up))))
    return lower..<upper
  }
}
